[package]
name = "dokany-sys"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
windows-sys = { version = "0.48.0", features = [ "Win32_Foundation", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_SystemServices" ] }
